import JSZip from "jszip";
import type {
  Assignment,
  CourseModule,
  CoursePage,
  CourseProject,
  Discussion,
  ExportMode,
  ExportValidationIssue,
  ExportValidationReport,
  ModuleItem,
  PublishState,
  Quiz,
  Rubric
} from "../types";
import { escapeXml, slugify, stripHtml } from "../utils/text";
import { buildReadinessReport } from "./readiness";

const CANVAS_NAMESPACE = "http://canvas.instructure.com/xsd/cccv1p0";
const CANVAS_XSD_URI = "https://canvas.instructure.com/xsd/cccv1p0.xsd";
const XSI = "http://www.w3.org/2001/XMLSchema-instance";
const CC_NAMESPACE = "http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1";
const LOM_RESOURCE = "http://ltsc.ieee.org/xsd/imsccv1p1/LOM/resource";
const LOM_MANIFEST = "http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest";
const QTI_NAMESPACE = "http://www.imsglobal.org/xsd/ims_qtiasiv1p2";

const resourceType = {
  webcontent: "webcontent",
  learningApplicationResource: "associatedcontent/imscc_xmlv1p1/learning-application-resource",
  discussionTopic: "imsdt_xmlv1p1",
  assessment: "imsqti_xmlv1p2/imscc_xmlv1p1/assessment"
};

const xml = (value: string | number | boolean | undefined | null): string => escapeXml(value == null ? value : String(value));

const pagePath = (page: CoursePage): string => page.assetPath ?? `wiki_content/${slugify(page.slug || page.title)}.html`;
const assignmentPath = (assignment: Assignment): string => `${assignment.id}/${slugify(assignment.title)}.html`;
const assignmentSettingsPath = (assignment: Assignment): string => `${assignment.id}/assignment_settings.xml`;
const discussionPath = (discussion: Discussion): string => `${discussion.id}.xml`;
const discussionMetaPath = (discussion: Discussion): string => `${discussion.id}_meta.xml`;
const quizCcPath = (quiz: Quiz): string => `${quiz.id}/assessment_qti.xml`;
const quizMetaPath = (quiz: Quiz): string => `${quiz.id}/assessment_meta.xml`;
const quizCanvasQtiPath = (quiz: Quiz): string => `non_cc_assessments/${quiz.id}.xml.qti`;

const canvasSchemaAttrs = `xmlns="${CANVAS_NAMESPACE}" xmlns:xsi="${XSI}" xsi:schemaLocation="${CANVAS_NAMESPACE} ${CANVAS_XSD_URI}"`;

const workflowState = (publishState: PublishState): "active" | "unpublished" => (publishState === "unpublished" ? "unpublished" : "active");

const htmlMeta = (fields: Record<string, string | number | boolean | undefined | null>): string =>
  Object.entries(fields)
    .filter(([, value]) => value !== undefined && value !== null && value !== "")
    .map(([key, value]) => `<meta name="${xml(key)}" content="${xml(String(value))}"/>`)
    .join("\n");

const wrappedHtmlDocument = (
  title: string,
  bodyHtml: string,
  metaFields: Record<string, string | number | boolean | undefined | null> = {}
): string => `<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>${xml(title)}</title>
${htmlMeta(metaFields)}
</head>
<body>
${bodyHtml}
</body>
</html>`;

const wrappedWikiPage = (page: CoursePage): string =>
  wrappedHtmlDocument(page.title, page.bodyHtml, {
    identifier: page.id,
    editing_roles: "teachers",
    notify_of_update: "false",
    workflow_state: workflowState(page.publishState),
    front_page: page.frontPage ? "true" : "false"
  });

const createBannerSvg = (course: CourseProject): string => `<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="360" viewBox="0 0 1440 360" role="img" aria-labelledby="title desc">
  <title id="title">${xml(course.title)} course banner</title>
  <desc id="desc">Abstract banner using the ${xml(course.theme.name)} theme.</desc>
  <rect width="1440" height="360" fill="${xml(course.theme.soft)}"/>
  <path d="M0 280 C 260 220 410 315 650 245 S 1020 160 1440 235 L1440 360 L0 360 Z" fill="${xml(course.theme.accent)}" opacity="0.18"/>
  <circle cx="1110" cy="120" r="74" fill="${xml(course.theme.accent)}" opacity="0.22"/>
  <rect x="96" y="82" width="560" height="170" rx="18" fill="#ffffff" opacity="0.92"/>
  <text x="132" y="150" font-family="Arial, sans-serif" font-size="44" font-weight="700" fill="#111827">${xml(course.title)}</text>
  <text x="132" y="200" font-family="Arial, sans-serif" font-size="24" fill="#374151">${xml(course.theme.bannerLabel)}</text>
</svg>`;

const createCourseTileSvg = (course: CourseProject): string => `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360" role="img" aria-labelledby="title desc">
  <title id="title">${xml(course.title)} course tile</title>
  <desc id="desc">Course tile placeholder generated by CourseForge.</desc>
  <rect width="640" height="360" rx="18" fill="${xml(course.theme.soft)}"/>
  <circle cx="510" cy="86" r="64" fill="${xml(course.theme.accent)}" opacity="0.22"/>
  <path d="M0 270 C120 210 220 315 340 260 C455 208 520 228 640 190 L640 360 L0 360 Z" fill="${xml(course.theme.accent)}" opacity="0.2"/>
  <rect x="48" y="58" width="420" height="190" rx="14" fill="#ffffff" opacity="0.93"/>
  <text x="76" y="126" font-family="Arial, sans-serif" font-size="34" font-weight="700" fill="#111827">${xml(course.title)}</text>
  <text x="76" y="176" font-family="Arial, sans-serif" font-size="18" fill="#374151">Canvas course shell</text>
</svg>`;

const pdfEscape = (value: string): string => value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

const createSimplePdf = (title: string, lines: string[]): string => {
  const clippedLines = [title, "", ...lines].flatMap((line) => line.match(/.{1,88}(\s|$)/g)?.map((part) => part.trim()) ?? [line]).slice(0, 46);
  const text = clippedLines
    .map((line, index) => `BT /F1 ${index === 0 ? 18 : 11} Tf 54 ${760 - index * 15} Td (${pdfEscape(line)}) Tj ET`)
    .join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${text.length} >>\nstream\n${text}\nendstream`
  ];
  let body = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(body.length);
    body += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = body.length;
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    body += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return body;
};

const createCanvasExportFlag = (): string => `Canvas export generated by CourseForge Canvas Builder.
This marker mirrors Canvas course export packages so Canvas uses the Canvas-flavored Common Cartridge importer.`;

const createCourseSettingsXml = (course: CourseProject): string => `<?xml version="1.0" encoding="UTF-8"?>
<course identifier="${xml(course.id)}" ${canvasSchemaAttrs}>
  <title>${xml(course.title)}</title>
  <course_code>${xml(slugify(course.title).slice(0, 24).toUpperCase())}</course_code>
  <default_view>wiki</default_view>
  <group_weighting_scheme>percent</group_weighting_scheme>
  <is_public>false</is_public>
  <public_syllabus>false</public_syllabus>
  <syllabus_course_summary>false</syllabus_course_summary>
  <allow_student_discussion_topics>false</allow_student_discussion_topics>
  <allow_student_forum_attachments>true</allow_student_forum_attachments>
  <show_total_grade_as_points>false</show_total_grade_as_points>
  <course_color>${xml(course.theme.accent)}</course_color>
</course>`;

const createContextInfoXml = (course: CourseProject): string => `<?xml version="1.0" encoding="UTF-8"?>
<context_info ${canvasSchemaAttrs}>
  <course_id>${xml(course.id)}</course_id>
  <course_name>${xml(course.title)}</course_name>
  <root_account_id>courseforge</root_account_id>
  <root_account_name>CourseForge Canvas Builder</root_account_name>
  <root_account_uuid>courseforge-local-mvp</root_account_uuid>
  <canvas_domain>canvas.instructure.com</canvas_domain>
</context_info>`;

const createCourseNavigationXml = (course: CourseProject): string => `<?xml version="1.0" encoding="UTF-8"?>
<courseNavigation ${canvasSchemaAttrs}>
${course.navigation
  .map(
    (item, index) => `  <tab identifier="${xml(item.id)}">
    <label>${xml(item.label)}</label>
    <position>${index + 1}</position>
    <hidden>${item.visible ? "false" : "true"}</hidden>
    <reason>${xml(item.reason)}</reason>
  </tab>`
  )
  .join("\n")}
</courseNavigation>`;

const createAssignmentXml = (assignment: Assignment): string => `<?xml version="1.0" encoding="UTF-8"?>
<assignment identifier="${xml(assignment.id)}" ${canvasSchemaAttrs}>
  <title>${xml(assignment.title)}</title>
  <workflow_state>${workflowState(assignment.publishState)}</workflow_state>
  <assignment_group_identifierref>${xml(assignment.assignmentGroupId)}</assignment_group_identifierref>
  <points_possible>${assignment.points}</points_possible>
  <grading_type>points</grading_type>
  ${assignment.dueAt ? `<due_at>${xml(assignment.dueAt)}</due_at>` : ""}
  <submission_types>online_text_entry,online_upload</submission_types>
  ${assignment.rubricId ? `<rubric_identifierref>${xml(assignment.rubricId)}</rubric_identifierref>` : ""}
  <description>${xml(stripHtml(assignment.descriptionHtml))}</description>
</assignment>`;

const createDiscussionXml = (discussion: Discussion): string => `<?xml version="1.0" encoding="UTF-8"?>
<topic xmlns="http://www.imsglobal.org/xsd/imsccv1p1/imsdt_v1p1" xmlns:xsi="${XSI}" xsi:schemaLocation="http://www.imsglobal.org/xsd/imsccv1p1/imsdt_v1p1 http://www.imsglobal.org/profile/cc/ccv1p1/ccv1p1_imsdt_v1p1.xsd">
  <title>${xml(discussion.title)}</title>
  <text texttype="text/html">${xml(discussion.promptHtml)}</text>
</topic>`;

const createDiscussionMetaXml = (discussion: Discussion): string => `<?xml version="1.0" encoding="UTF-8"?>
<topicMeta identifier="${xml(`${discussion.id}_meta`)}" ${canvasSchemaAttrs}>
  <topic_id>${xml(discussion.id)}</topic_id>
  <title>${xml(discussion.title)}</title>
  <type>topic</type>
  <workflow_state>${workflowState(discussion.publishState)}</workflow_state>
  <discussion_type>threaded</discussion_type>
  <require_initial_post>true</require_initial_post>
  ${
    discussion.points > 0
      ? `<assignment identifier="${xml(`${discussion.id}_assignment`)}">
    <title>${xml(discussion.title)}</title>
    <points_possible>${discussion.points}</points_possible>
    <grading_type>points</grading_type>
    ${discussion.dueAt ? `<due_at>${xml(discussion.dueAt)}</due_at>` : ""}
    <assignment_group_identifierref>${xml(discussion.assignmentGroupId)}</assignment_group_identifierref>
    ${discussion.rubricId ? `<rubric_identifierref>${xml(discussion.rubricId)}</rubric_identifierref>` : ""}
  </assignment>`
      : ""
  }
</topicMeta>`;

const createRubricsXml = (rubrics: Rubric[]): string => `<?xml version="1.0" encoding="UTF-8"?>
<rubrics ${canvasSchemaAttrs}>
${rubrics
  .map(
    (rubric) => `  <rubric identifier="${xml(rubric.id)}">
    <title>${xml(rubric.title)}</title>
    <reusable>false</reusable>
    <public>false</public>
    <workflow_state>${workflowState(rubric.publishState)}</workflow_state>
    <points_possible>${rubric.points}</points_possible>
    <aligned_outcome_identifierrefs>${xml(rubric.alignedOutcomeIds.join(","))}</aligned_outcome_identifierrefs>
    <free_form_criterion_comments>false</free_form_criterion_comments>
    <criteria>
${rubric.criteria
  .map(
    (criterion) => `      <criterion>
        <criterion_id>${xml(criterion.id)}</criterion_id>
        <points>${Math.max(...criterion.levels.map((level) => level.points))}</points>
        <description>${xml(criterion.title)}</description>
        <long_description>${xml(criterion.description)}</long_description>
        ${criterion.outcomeId ? `<learning_outcome_identifierref>${xml(criterion.outcomeId)}</learning_outcome_identifierref>` : ""}
        <ratings>
${criterion.levels
  .map(
    (level) => `          <rating>
            <description>${xml(level.label)}</description>
            <points>${level.points}</points>
            <criterion_id>${xml(criterion.id)}</criterion_id>
            <long_description>${xml(level.description)}</long_description>
          </rating>`
  )
  .join("\n")}
        </ratings>
      </criterion>`
  )
  .join("\n")}
    </criteria>
  </rubric>`
  )
  .join("\n")}
</rubrics>`;

const createAssignmentGroupsXml = (course: CourseProject): string => `<?xml version="1.0" encoding="UTF-8"?>
<assignmentGroups ${canvasSchemaAttrs}>
${course.assignmentGroups
  .map(
    (group, index) => `  <assignmentGroup identifier="${xml(group.id)}">
    <title>${xml(group.name)}</title>
    <position>${index + 1}</position>
    <group_weight>${group.weight}</group_weight>
    ${
      group.dropLowest
        ? `<rules><rule><drop_type>drop_lowest</drop_type><drop_count>${group.dropLowest}</drop_count></rule></rules>`
        : ""
    }
  </assignmentGroup>`
  )
  .join("\n")}
</assignmentGroups>`;

const createLearningOutcomesXml = (course: CourseProject): string => `<?xml version="1.0" encoding="UTF-8"?>
<learningOutcomes ${canvasSchemaAttrs}>
${course.outcomes
  .map(
    (outcome) => `  <learningOutcome identifier="${xml(outcome.id)}">
    <title>${xml(outcome.code)}</title>
    <description>${xml(outcome.text)}</description>
    <calculation_method>decaying_average</calculation_method>
    <calculation_int>65</calculation_int>
    <points_possible>5</points_possible>
    <mastery_points>3</mastery_points>
    <ratings>
      <rating><description>Exceeds mastery</description><points>5</points></rating>
      <rating><description>Meets mastery</description><points>3</points></rating>
      <rating><description>Developing</description><points>1</points></rating>
    </ratings>
  </learningOutcome>`
  )
  .join("\n")}
</learningOutcomes>`;

const itemContentType = (item: ModuleItem): string => {
  if (item.type === "page" || item.type === "syllabus") return "WikiPage";
  if (item.type === "assignment") return "Assignment";
  if (item.type === "discussion") return "DiscussionTopic";
  if (item.type === "quiz") return "Quizzes::Quiz";
  return "WikiPage";
};

const createModuleMetaXml = (course: CourseProject): string => `<?xml version="1.0" encoding="UTF-8"?>
<modules ${canvasSchemaAttrs}>
${course.modules
  .map(
    (module: CourseModule) => `  <module identifier="${xml(module.id)}">
    <title>${xml(module.title)}</title>
    <workflow_state>${workflowState(module.publishState)}</workflow_state>
    <position>${module.order}</position>
    <items>
${module.items
  .map(
    (item) => `      <item identifier="${xml(item.id)}">
        <content_type>${itemContentType(item)}</content_type>
        <workflow_state>${workflowState(item.publishState)}</workflow_state>
        <title>${xml(item.title)}</title>
        <identifierref>${xml(item.refId)}</identifierref>
        <position>${item.order}</position>
        <indent>${item.indent}</indent>
      </item>`
  )
  .join("\n")}
    </items>
  </module>`
  )
  .join("\n")}
</modules>`;

const createAssessmentQtiXml = (quiz: Quiz, canvasFlavor: boolean): string => `<?xml version="1.0" encoding="UTF-8"?>
<questestinterop xmlns="${QTI_NAMESPACE}" xmlns:xsi="${XSI}" xsi:schemaLocation="${QTI_NAMESPACE} ${
  canvasFlavor ? "http://www.imsglobal.org/xsd/ims_qtiasiv1p2p1.xsd" : "http://www.imsglobal.org/profile/cc/ccv1p1/ccv1p1_qtiasiv1p2p1_v1p0.xsd"
}">
  <assessment ident="${xml(quiz.id)}" title="${xml(quiz.title)}">
    <qtimetadata>
      ${canvasFlavor ? "" : "<qtimetadatafield><fieldlabel>cc_profile</fieldlabel><fieldentry>cc.exam.v0p1</fieldentry></qtimetadatafield>"}
      ${canvasFlavor ? "" : "<qtimetadatafield><fieldlabel>qmd_assessmenttype</fieldlabel><fieldentry>Examination</fieldentry></qtimetadatafield>"}
      ${canvasFlavor ? "" : "<qtimetadatafield><fieldlabel>qmd_scoretype</fieldlabel><fieldentry>Percentage</fieldentry></qtimetadatafield>"}
      <qtimetadatafield><fieldlabel>points_possible</fieldlabel><fieldentry>${quiz.points}</fieldentry></qtimetadatafield>
      <qtimetadatafield><fieldlabel>cc_maxattempts</fieldlabel><fieldentry>1</fieldentry></qtimetadatafield>
      <qtimetadatafield><fieldlabel>aligned_outcome_identifierrefs</fieldlabel><fieldentry>${xml(quiz.alignedOutcomeIds.join(","))}</fieldentry></qtimetadatafield>
    </qtimetadata>
    <section ident="root_section">
${quiz.questions
  .map(
    (question) => `      <item ident="${xml(question.id)}" title="${xml(question.stem.slice(0, 72))}">
        <presentation>
          <material><mattext texttype="text/html">${xml(question.stem)}</mattext></material>
        </presentation>
        <itemmetadata>
          <qtimetadata>
            <qtimetadatafield><fieldlabel>question_type</fieldlabel><fieldentry>${xml(question.type)}</fieldentry></qtimetadatafield>
            <qtimetadatafield><fieldlabel>points_possible</fieldlabel><fieldentry>${question.points}</fieldentry></qtimetadatafield>
          </qtimetadata>
        </itemmetadata>
      </item>`
  )
  .join("\n")}
    </section>
  </assessment>
</questestinterop>`;

const createAssessmentMetaXml = (quiz: Quiz): string => `<?xml version="1.0" encoding="UTF-8"?>
<quiz identifier="${xml(quiz.id)}" ${canvasSchemaAttrs}>
  <title>${xml(quiz.title)}</title>
  <description>${xml(quiz.purpose)}</description>
  <workflow_state>${workflowState(quiz.publishState)}</workflow_state>
  <shuffle_answers>false</shuffle_answers>
  <scoring_policy>keep_highest</scoring_policy>
  <hide_results></hide_results>
  <quiz_type>assignment</quiz_type>
  <points_possible>${quiz.points}</points_possible>
  ${quiz.dueAt ? `<due_at>${xml(quiz.dueAt)}</due_at>` : ""}
  <allowed_attempts>1</allowed_attempts>
  <one_question_at_a_time>false</one_question_at_a_time>
  <cant_go_back>false</cant_go_back>
  <available>true</available>
  <assignment_group_identifierref>${xml(quiz.assignmentGroupId)}</assignment_group_identifierref>
  <aligned_outcome_identifierrefs>${xml(quiz.alignedOutcomeIds.join(","))}</aligned_outcome_identifierrefs>
</quiz>`;

const createManifest = (course: CourseProject): string => {
  const courseSettingsFiles = [
    "course_settings/course_settings.xml",
    "course_settings/module_meta.xml",
    "course_settings/assignment_groups.xml",
    "course_settings/rubrics.xml",
    "course_settings/learning_outcomes.xml",
    "course_settings/course_navigation.xml",
    "course_settings/context.xml",
    "course_settings/canvas_export.txt"
  ];

  const pageResources = course.pages
    .map(
      (page) => `    <resource identifier="${xml(page.id)}" type="${resourceType.webcontent}" href="${xml(pagePath(page))}">
      <file href="${xml(pagePath(page))}" />
    </resource>`
    )
    .join("\n");

  const assignmentResources = course.assignments
    .map(
      (assignment) => `    <resource identifier="${xml(assignment.id)}" type="${resourceType.learningApplicationResource}" href="${xml(assignmentPath(assignment))}">
      <file href="${xml(assignmentPath(assignment))}" />
      <file href="${xml(assignmentSettingsPath(assignment))}" />
    </resource>`
    )
    .join("\n");

  const discussionResources = course.discussions
    .map(
      (discussion) => `    <resource identifier="${xml(discussion.id)}" type="${resourceType.discussionTopic}">
      <file href="${xml(discussionPath(discussion))}" />
      <dependency identifierref="${xml(`${discussion.id}_meta`)}" />
    </resource>
    <resource identifier="${xml(`${discussion.id}_meta`)}" type="${resourceType.learningApplicationResource}" href="${xml(discussionMetaPath(discussion))}">
      <file href="${xml(discussionMetaPath(discussion))}" />
    </resource>`
    )
    .join("\n");

  const quizResources = course.quizzes
    .map(
      (quiz) => `    <resource identifier="${xml(quiz.id)}" type="${resourceType.assessment}">
      <file href="${xml(quizCcPath(quiz))}" />
      <dependency identifierref="${xml(`${quiz.id}_canvas`)}" />
    </resource>
    <resource identifier="${xml(`${quiz.id}_canvas`)}" type="${resourceType.learningApplicationResource}" href="${xml(quizMetaPath(quiz))}">
      <file href="${xml(quizMetaPath(quiz))}" />
      <file href="${xml(quizCanvasQtiPath(quiz))}" />
    </resource>`
    )
    .join("\n");

  const assetResources = course.fileAssets
    .map(
      (asset) => `    <resource identifier="${xml(asset.id)}" type="${resourceType.webcontent}" href="${xml(asset.path)}">
      <file href="${xml(asset.path)}" />
    </resource>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="${xml(`common_cartridge_${course.id}`)}"
  xmlns="${CC_NAMESPACE}"
  xmlns:lom="${LOM_RESOURCE}"
  xmlns:lomimscc="${LOM_MANIFEST}"
  xmlns:xsi="${XSI}"
  xsi:schemaLocation="${CC_NAMESPACE} http://www.imsglobal.org/profile/cc/ccv1p1/ccv1p1_imscp_v1p2_v1p0.xsd ${LOM_RESOURCE} http://www.imsglobal.org/profile/cc/ccv1p1/LOM/ccv1p1_lomresource_v1p0.xsd ${LOM_MANIFEST} http://www.imsglobal.org/profile/cc/ccv1p1/LOM/ccv1p1_lommanifest_v1p0.xsd">
  <metadata>
    <schema>IMS Common Cartridge</schema>
    <schemaversion>1.1.0</schemaversion>
    <lomimscc:lom>
      <lomimscc:general><lomimscc:title><lomimscc:string>${xml(course.title)}</lomimscc:string></lomimscc:title></lomimscc:general>
      <lomimscc:lifeCycle><lomimscc:contribute><lomimscc:date><lomimscc:dateTime>${new Date().toISOString()}</lomimscc:dateTime></lomimscc:date></lomimscc:contribute></lomimscc:lifeCycle>
    </lomimscc:lom>
  </metadata>
  <organizations>
    <organization identifier="org_${xml(course.id)}" structure="rooted-hierarchy">
      <title>${xml(course.title)}</title>
${course.modules
  .map(
    (module) => `      <item identifier="${xml(`${module.id}_org`)}">
        <title>${xml(module.title)}</title>
${module.items
  .map((item) => `        <item identifier="${xml(`${item.id}_org`)}" identifierref="${xml(item.refId)}"><title>${xml(item.title)}</title></item>`)
  .join("\n")}
      </item>`
  )
  .join("\n")}
    </organization>
  </organizations>
  <resources>
    <resource identifier="${xml(course.id)}" type="${resourceType.learningApplicationResource}" href="course_settings/canvas_export.txt">
${courseSettingsFiles.map((file) => `      <file href="${xml(file)}" />`).join("\n")}
    </resource>
    <resource identifier="${xml(`${course.id}_syllabus`)}" type="${resourceType.learningApplicationResource}" href="course_settings/syllabus.html" intendeduse="syllabus">
      <file href="course_settings/syllabus.html" />
    </resource>
${pageResources}
${assignmentResources}
${discussionResources}
${quizResources}
${assetResources}
  </resources>
</manifest>`;
};

const printableHtml = (title: string, bodyHtml: string): string =>
  wrappedHtmlDocument(
    title,
    `<div style="font-family: Arial, sans-serif; color: #111827; line-height: 1.55; max-width: 760px; margin: 0 auto;">${bodyHtml}</div>`,
    { printable: "true" }
  );

export const buildImsccZip = async (course: CourseProject): Promise<JSZip> => {
  const zip = new JSZip();
  const syllabusPage = course.pages.find((page) => page.slug === "syllabus");
  const instructorGuidePage = course.pages.find((page) => page.slug === "instructor-guide");

  zip.file("imsmanifest.xml", createManifest(course));
  zip.file("course_settings/course_settings.xml", createCourseSettingsXml(course));
  zip.file("course_settings/module_meta.xml", createModuleMetaXml(course));
  zip.file("course_settings/assignment_groups.xml", createAssignmentGroupsXml(course));
  zip.file("course_settings/rubrics.xml", createRubricsXml(course.rubrics));
  zip.file("course_settings/learning_outcomes.xml", createLearningOutcomesXml(course));
  zip.file("course_settings/course_navigation.xml", createCourseNavigationXml(course));
  zip.file("course_settings/context.xml", createContextInfoXml(course));
  zip.file("course_settings/canvas_export.txt", createCanvasExportFlag());
  zip.file("course_settings/syllabus.html", wrappedHtmlDocument("Syllabus", syllabusPage?.bodyHtml ?? ""));
  zip.file("web_resources/course-banner.svg", createBannerSvg(course));
  zip.file("web_resources/course-tile.svg", createCourseTileSvg(course));
  zip.file("web_resources/syllabus-printable.html", printableHtml("Printable Syllabus", syllabusPage?.bodyHtml ?? ""));
  zip.file(
    "web_resources/syllabus-printable.pdf",
    createSimplePdf(`${course.title} Syllabus`, [
      stripHtml(syllabusPage?.bodyHtml ?? "").slice(0, 2800),
      "Generated by CourseForge. Review in Canvas before publishing."
    ])
  );
  zip.file("web_resources/instructor-guide-printable.html", printableHtml("Instructor Guide", instructorGuidePage?.bodyHtml ?? ""));
  zip.file(
    "web_resources/instructor-guide.pdf",
    createSimplePdf("Instructor Guide", [
      stripHtml(instructorGuidePage?.bodyHtml ?? "").slice(0, 2800),
      "Canvas sandbox import verification is still required."
    ])
  );

  course.pages.forEach((page) => {
    zip.file(pagePath(page), wrappedWikiPage(page));
  });

  course.assignments.forEach((assignment) => {
    zip.file(assignmentPath(assignment), wrappedHtmlDocument(`Assignment: ${assignment.title}`, assignment.descriptionHtml));
    zip.file(assignmentSettingsPath(assignment), createAssignmentXml(assignment));
  });

  course.discussions.forEach((discussion) => {
    zip.file(discussionPath(discussion), createDiscussionXml(discussion));
    zip.file(discussionMetaPath(discussion), createDiscussionMetaXml(discussion));
  });

  course.quizzes.forEach((quiz) => {
    zip.file(quizCcPath(quiz), createAssessmentQtiXml(quiz, false));
    zip.file(quizMetaPath(quiz), createAssessmentMetaXml(quiz));
    zip.file(quizCanvasQtiPath(quiz), createAssessmentQtiXml(quiz, true));
  });

  zip.file(
    "courseforge-readme.txt",
    [
      "CourseForge Canvas Builder export",
      `Export mode: ${course.exportMode}`,
      "This package is generated from structured course data.",
      "The package includes Canvas-flavored course metadata, navigation defaults, assignment groups, rubrics, outcomes, guide assets, and Common Cartridge resources.",
      "Canvas may duplicate edited objects when reimporting into an existing course.",
      "Canvas sandbox import verification is still required before production compatibility claims."
    ].join("\n")
  );

  return zip;
};

const htmlBlocks = (course: CourseProject): Array<{ id: string; title: string; html: string }> => [
  ...course.pages.map((page) => ({ id: page.id, title: page.title, html: page.bodyHtml })),
  ...course.assignments.map((assignment) => ({ id: assignment.id, title: assignment.title, html: assignment.descriptionHtml })),
  ...course.discussions.map((discussion) => ({ id: discussion.id, title: discussion.title, html: discussion.promptHtml }))
];

const hrefsFrom = (html: string): string[] => Array.from(html.matchAll(/href\s*=\s*["']([^"']*)["']/gi)).map((match) => match[1].trim());
const unsafeHtml = (html: string): boolean => /<script[\s>]/i.test(html) || /\son[a-z]+\s*=/i.test(html) || /<iframe[\s>]/i.test(html) || /<object[\s>]/i.test(html);
const placeholderHref = (href: string): boolean => href === "" || href === "#" || /^javascript:/i.test(href) || href.includes("TODO_LINK");
const externalHref = (href: string): boolean => /^(https?:|mailto:|tel:)/i.test(href);
const normalizeHref = (href: string): string => href.split("#")[0].split("?")[0].replace(/^\.\//, "");
const pageLinkTargets = (course: CourseProject): Set<string> =>
  new Set(course.pages.flatMap((page) => [page.slug, `${slugify(page.slug || page.title)}.html`, `wiki_content/${slugify(page.slug || page.title)}.html`]));
const resourceLinkTargets = (course: CourseProject): Set<string> =>
  new Set(course.fileAssets.flatMap((asset) => [asset.path, `../${asset.path}`, asset.fileName]));
const dateOnly = (iso?: string): string | undefined => iso?.slice(0, 10);
const dateInTerm = (iso: string | undefined, start?: string, end?: string): boolean => {
  const value = dateOnly(iso);
  if (!value) return false;
  if (start && value < start) return false;
  if (end && value > end) return false;
  return true;
};
const isBlockedDate = (iso: string | undefined, blockedDates: Set<string>): boolean => {
  const value = dateOnly(iso);
  return Boolean(value && blockedDates.has(value));
};

export const validateImsccZip = async (course: CourseProject, zip: JSZip): Promise<ExportValidationReport> => {
  const files = Object.keys(zip.files).filter((path) => !zip.files[path].dir).sort();
  const issues: ExportValidationIssue[] = [];
  const readiness = buildReadinessReport(course);
  const fail = (id: string, message: string): void => {
    issues.push({ id, message, severity: "error" });
  };
  const warn = (id: string, message: string): void => {
    issues.push({ id, message, severity: "warning" });
  };

  if (!zip.file("imsmanifest.xml")) fail("manifest-missing", "imsmanifest.xml is required.");
  if (!zip.file("course_settings/canvas_export.txt")) fail("canvas-export-flag-missing", "course_settings/canvas_export.txt is required for Canvas-flavored course exports.");
  if (!zip.file("course_settings/course_settings.xml")) fail("course-settings-missing", "course_settings/course_settings.xml is required.");
  if (!zip.file("course_settings/module_meta.xml")) fail("module-meta-missing", "course_settings/module_meta.xml is required for Canvas module order.");
  if (!zip.file("course_settings/assignment_groups.xml")) fail("assignment-groups-missing", "course_settings/assignment_groups.xml is required for gradebook grouping.");
  if (!zip.file("course_settings/course_navigation.xml")) warn("navigation-missing", "course_settings/course_navigation.xml was not found.");
  if (!zip.file("course_settings/rubrics.xml")) warn("rubrics-missing", "course_settings/rubrics.xml was not found.");
  if (!zip.file("course_settings/learning_outcomes.xml")) warn("outcomes-missing", "course_settings/learning_outcomes.xml was not found.");
  if (!zip.file("web_resources/syllabus-printable.pdf")) fail("syllabus-pdf-missing", "Printable syllabus PDF is missing.");
  if (!zip.file("web_resources/instructor-guide.pdf")) fail("instructor-guide-pdf-missing", "Instructor guide PDF is missing.");

  const groupIds = new Set(course.assignmentGroups.map((group) => group.id));
  const activeGroupUse = new Map<string, number>();
  const rubricIds = new Set(course.rubrics.map((rubric) => rubric.id));
  const outcomeIds = new Set(course.outcomes.map((outcome) => outcome.id));
  const blockedDates = new Set([...(course.settings.schedule.holidays ?? []), ...(course.settings.schedule.blackoutDates ?? [])]);
  const validateDueDate = (id: string, title: string, dueAt: string | undefined): void => {
    if (!course.settings.schedule.enableDueDates) return;
    if (!dueAt) {
      fail(`due-date-missing-${id}`, `${title} is missing a due date while due dates are enabled.`);
      return;
    }
    if (!dateInTerm(dueAt, course.settings.schedule.termStartDate, course.settings.schedule.termEndDate) && !course.settings.schedule.allowDueDatesOutsideTerm) {
      fail(`due-date-outside-term-${id}`, `${title} has a due date outside the configured term.`);
    }
    if (isBlockedDate(dueAt, blockedDates)) fail(`due-date-blocked-${id}`, `${title} is due on a holiday or blackout date.`);
  };

  course.assignments.forEach((assignment) => {
    if (!zip.file(assignmentPath(assignment))) fail(`missing-assignment-${assignment.id}`, `Missing assignment HTML for ${assignment.title}.`);
    if (!zip.file(assignmentSettingsPath(assignment))) fail(`missing-assignment-settings-${assignment.id}`, `Missing assignment settings for ${assignment.title}.`);
    if (!groupIds.has(assignment.assignmentGroupId)) fail(`assignment-group-${assignment.id}`, `${assignment.title} references a missing assignment group.`);
    activeGroupUse.set(assignment.assignmentGroupId, (activeGroupUse.get(assignment.assignmentGroupId) ?? 0) + 1);
    if (!assignment.rubricId || !rubricIds.has(assignment.rubricId)) fail(`assignment-rubric-${assignment.id}`, `${assignment.title} is missing a valid rubric reference.`);
    if (assignment.alignedOutcomeIds.length === 0 || assignment.alignedOutcomeIds.some((outcomeId) => !outcomeIds.has(outcomeId))) fail(`assignment-outcomes-${assignment.id}`, `${assignment.title} is missing valid outcome alignment.`);
    validateDueDate(assignment.id, assignment.title, assignment.dueAt);
  });

  course.discussions.forEach((discussion) => {
    if (!zip.file(discussionPath(discussion))) fail(`missing-discussion-${discussion.id}`, `Missing discussion topic file for ${discussion.title}.`);
    if (!zip.file(discussionMetaPath(discussion))) fail(`missing-discussion-meta-${discussion.id}`, `Missing discussion metadata for ${discussion.title}.`);
    if (discussion.points > 0) {
      if (!groupIds.has(discussion.assignmentGroupId)) fail(`discussion-group-${discussion.id}`, `${discussion.title} references a missing assignment group.`);
      activeGroupUse.set(discussion.assignmentGroupId, (activeGroupUse.get(discussion.assignmentGroupId) ?? 0) + 1);
      if (!discussion.rubricId || !rubricIds.has(discussion.rubricId)) fail(`discussion-rubric-${discussion.id}`, `${discussion.title} is missing a valid rubric reference.`);
      if (discussion.alignedOutcomeIds.length === 0 || discussion.alignedOutcomeIds.some((outcomeId) => !outcomeIds.has(outcomeId))) fail(`discussion-outcomes-${discussion.id}`, `${discussion.title} is missing valid outcome alignment.`);
      validateDueDate(discussion.id, discussion.title, discussion.dueAt);
    }
  });

  course.quizzes.forEach((quiz) => {
    if (!zip.file(quizCcPath(quiz))) fail(`missing-quiz-qti-${quiz.id}`, `Missing Common Cartridge QTI file for ${quiz.title}.`);
    if (!zip.file(quizMetaPath(quiz))) fail(`missing-quiz-meta-${quiz.id}`, `Missing Canvas quiz metadata for ${quiz.title}.`);
    if (!zip.file(quizCanvasQtiPath(quiz))) fail(`missing-quiz-canvas-qti-${quiz.id}`, `Missing Canvas-flavored QTI file for ${quiz.title}.`);
    if (!groupIds.has(quiz.assignmentGroupId)) fail(`quiz-group-${quiz.id}`, `${quiz.title} references a missing assignment group.`);
    activeGroupUse.set(quiz.assignmentGroupId, (activeGroupUse.get(quiz.assignmentGroupId) ?? 0) + 1);
    if (quiz.alignedOutcomeIds.length === 0 || quiz.alignedOutcomeIds.some((outcomeId) => !outcomeIds.has(outcomeId))) fail(`quiz-outcomes-${quiz.id}`, `${quiz.title} is missing valid outcome alignment.`);
    validateDueDate(quiz.id, quiz.title, quiz.dueAt);
  });

  course.rubrics.forEach((rubric) => {
    if (rubric.alignedOutcomeIds.length === 0 || rubric.alignedOutcomeIds.some((outcomeId) => !outcomeIds.has(outcomeId))) {
      fail(`rubric-outcomes-${rubric.id}`, `${rubric.title} is missing valid outcome alignment.`);
    }
  });

  const groupTotal = course.assignmentGroups.reduce((sum, group) => sum + Number(group.weight || 0), 0);
  if (Math.round(groupTotal) !== 100) fail("assignment-group-total", `Assignment group weights total ${groupTotal}%, not 100%.`);
  course.assignmentGroups.forEach((group) => {
    if ((activeGroupUse.get(group.id) ?? 0) > 0 && Number(group.weight) === 0) fail(`assignment-group-zero-${group.id}`, `${group.name} has graded items but 0% weight.`);
  });

  const finalModule = course.modules.find((module) => module.kind === "final");
  const instructorModule = course.modules.find((module) => module.kind === "instructor");
  if (!finalModule) fail("final-module-missing", "Final Project module is required.");
  if (!instructorModule) fail("instructor-module-missing", "Instructor Guide module is required.");
  if (instructorModule && instructorModule.publishState !== "unpublished") fail("instructor-module-published", "Instructor Guide module must be unpublished by default.");

  course.modules
    .filter((module) => module.kind === "content")
    .forEach((module) => {
      if (!module.items.some((item) => item.type === "page" && /overview/i.test(item.title))) fail(`module-overview-${module.id}`, `${module.title} is missing an overview page.`);
      if (!module.items.some((item) => item.type === "page" && /(wrap|recap)/i.test(item.title))) fail(`module-recap-${module.id}`, `${module.title} is missing a recap/wrap-up page.`);
    });

  course.pages.forEach((page) => {
    if (!zip.file(pagePath(page))) fail(`missing-page-${page.id}`, `Missing page file for ${page.title}.`);
  });

  htmlBlocks(course).forEach((block) => {
    if (unsafeHtml(block.html)) fail(`unsafe-html-${block.id}`, `${block.title} includes Canvas-hostile HTML.`);
    hrefsFrom(block.html).forEach((href) => {
      if (placeholderHref(href)) fail(`placeholder-link-${block.id}`, `${block.title} includes a placeholder or unsafe link: ${href || "(empty)"}.`);
    });
  });

  const knownPageTargets = pageLinkTargets(course);
  const knownResourceTargets = resourceLinkTargets(course);
  htmlBlocks(course).forEach((block) => {
    hrefsFrom(block.html)
      .filter((href) => !placeholderHref(href) && !externalHref(href) && !href.startsWith("#"))
      .forEach((href) => {
        const normalized = normalizeHref(href);
        if (normalized && !knownPageTargets.has(normalized) && !knownResourceTargets.has(normalized)) {
          warn(`broken-internal-link-${block.id}-${slugify(href).slice(0, 40)}`, `${block.title} links to missing internal content or file: ${href}.`);
        }
      });
  });

  course.modules.forEach((module) => {
    module.items.forEach((item) => {
      const exists =
        course.pages.some((page) => page.id === item.refId) ||
        course.assignments.some((assignment) => assignment.id === item.refId) ||
        course.discussions.some((discussion) => discussion.id === item.refId) ||
        course.quizzes.some((quiz) => quiz.id === item.refId);
      if (!exists) fail(`broken-module-ref-${item.id}`, `Module item "${item.title}" references a missing object.`);
    });
  });

  if (readiness.blockers > 0) {
    warn("readiness-blockers", `${readiness.blockers} readiness blocker(s) should be resolved before Canvas import.`);
  }

  const manifestText = await zip.file("imsmanifest.xml")?.async("text");
  const resourceIds = new Set(Array.from(manifestText?.matchAll(/<resource\s+identifier="([^"]+)"/g) ?? []).map((match) => match[1]));
  const identifierRefs = Array.from(manifestText?.matchAll(/identifierref="([^"]+)"/g) ?? []).map((match) => match[1]);
  identifierRefs.forEach((ref) => {
    if (!resourceIds.has(ref)) fail(`missing-resource-${ref}`, `Manifest identifierref ${ref} does not point to a resource.`);
  });

  const fileRefs = Array.from(manifestText?.matchAll(/<file\s+href="([^"]+)"/g) ?? []).map((match) => match[1]);
  fileRefs.forEach((ref) => {
    if (!zip.file(ref)) fail(`missing-file-${ref}`, `Manifest file reference ${ref} is missing from the package.`);
  });

  const errorCount = issues.filter((issue) => issue.severity === "error").length;
  const warningCount = issues.filter((issue) => issue.severity === "warning").length;

  return {
    valid: errorCount === 0,
    score: Math.max(0, 100 - errorCount * 18 - warningCount * 5),
    packageName: `${slugify(course.title)}.imscc`,
    checkedAt: new Date().toISOString(),
    issues,
    files,
    sandboxImportStatus: "not_tested"
  };
};

export const generateImsccBlob = async (
  course: CourseProject,
  mode: ExportMode = course.exportMode
): Promise<{ blob: Blob; report: ExportValidationReport; fileName: string }> => {
  const exportCourse: CourseProject = { ...course, exportMode: mode };
  const zip = await buildImsccZip(exportCourse);
  const report = await validateImsccZip(exportCourse, zip);
  const blob = await zip.generateAsync({ type: "blob", mimeType: "application/zip" });
  return { blob, report, fileName: report.packageName };
};
