// ============================================================================
// Syllabus PDF export
// ----------------------------------------------------------------------------
// A clean, printable PDF of the course syllabus, built from the same syllabus
// page that becomes the Canvas syllabus — so the PDF and the Canvas page stay
// aligned. Falls back gracefully if no dedicated syllabus page exists.
// ============================================================================

import type { CourseProject, CoursePage } from "../types";
import { slugify, stripHtml } from "../utils/text";
import { PdfDoc } from "./pdfDoc";

/** The page that backs the Canvas syllabus (slug "syllabus"), if present. */
export const findSyllabusPage = (course: CourseProject): CoursePage | undefined =>
  course.pages.find((page) => page.slug === "syllabus") ??
  course.pages.find((page) => /syllabus/i.test(page.title));

export const buildSyllabusPdfBlob = (course: CourseProject): Blob => {
  const doc = new PdfDoc();
  const syllabus = findSyllabusPage(course);

  doc.title(course.title || "Course Syllabus");
  doc.para("Course Syllabus");
  if (course.description) doc.para(course.description);
  doc.spacer(6);

  if (course.outcomes.length) {
    doc.heading("Course Learning Outcomes", 14);
    course.outcomes.forEach((outcome) => doc.bullet(`${outcome.code}: ${outcome.text}`));
    doc.spacer(4);
  }

  if (syllabus) {
    // Render the syllabus page body as readable prose. The HTML uses headings and lists; stripHtml
    // keeps the text and the PdfDoc paragraph wrapping handles layout.
    const text = stripHtml(syllabus.bodyHtml);
    text
      .split(/\n{2,}|\r\n\r\n/)
      .map((block) => block.trim())
      .filter(Boolean)
      .forEach((block) => doc.para(block));
  } else {
    doc.para("No dedicated syllabus page was found in this course. Add a syllabus in the Syllabus tab to export it here.");
  }

  doc.spacer(8);
  doc.para(
    "This PDF mirrors the Canvas syllabus page generated by RocketCourse. Review dates, policies, grading, and " +
      "institutional requirements before publishing to students."
  );
  return doc.blob();
};

export const syllabusPdfFileName = (course: CourseProject): string => `${slugify(course.title || "course")}-syllabus.pdf`;
